apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: digitalocean-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: digitalocean-creds
      key: creds

