kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata: 
  name: test-crossplane2
spec:
  name: test-crossplane2
  pools:
    - id: "8382e422-dcdd-461f-afb4-2ab67f171c3e"
      count: 1
      size: g3.k3s.small
  applications: 
    - "argo-cd"
    - "prometheus-operator"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider

