apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: aks-resource
spec:
  location: eastus

---

apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: azure
spec:
  location: eastus
  version: "1.19.7"
  nodeVMSize: Standard_D2_v2
  resourceGroupNameRef:
    name: aks-resource
  dnsNamePrefix: dt
  nodeCount: 2
