apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  labels:
    example: "true"
  name: akscluster
spec:
  disableRBAC: false
  dnsNamePrefix: crossplane-aks
  location: West US 2
  nodeCount: 1
  nodeVMSize: Standard_B2s
  providerConfigRef:
    name: azure-provider
  resourceGroupNameRef:
    name: example-rg
  version: 1.19.11
  vnetSubnetIDRef:
    name: example-sub
  writeConnectionSecretToRef:
    name: example-akscluster
    namespace: crossplane-system
