apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
 name: aks-cluster
 labels:
   cloud-provider: aks 
spec:
 clusterNetwork:
   services:
     cidrBlocks: ["10.0.0.0/16"] 
   pods:
     cidrBlocks: ["10.244.0.0/16"] 
   serviceDomain: "cluster.local" 
 providerSpec:
   value:
     apiVersion: "aksprovider/v1alpha1"
     kind: "AKSClusterProviderSpec"
     spec:
       secretName: azure-creds
       location: "eastus" 
       resourceGroupName: "testAksResourceGroup" 
       nodeCount: 1 
       kubernetesVersion: "1.14.6" 
       nodeOsdiskSize: 100.
       dnsServiceIP: 10.0.0.10
